### ISSUE TITLE
Vue as individual page

### ISSUE THREAD

**Issue by saknarak** [rigor789/nativescript-vue#47]
Is possible to use Vue in a page

app.js
---
require("./bundle-config");
var application = require("application");
application.start({ moduleName: "views/login/login" });

view/login/login.js
exports = new Vue({...})

something like this

**Comment by rigor789** [comment]
Yes and no!

Yes, you can use separate pages as shown in the sample app here: https://github.com/rigor789/nativescript-vue/blob/master/samples/app/app-with-router-pages.js

And no because it requires vue-router to work.

Ideally we would like to have a way to navigate between pages without vue router, and then make the router an option for those who need it.

**Comment by saknarak** [comment]
Thank you. Your example very clear.

**Comment by rigor789** [comment]
Hey, I haven't tested the back button yet, that is on the roadmap, but you should be able to create different pages (activities) if you use the example I linked, where every component has a `<page>` root element.

Using the router, you should be able to navigate between the pages, but this is still a very minimal and early implementation! If you find any bugs, issues please let us know, so we can work on fixing them!

**Comment by saknarak** [comment]
Hope this can help someone that has issue with router-page

```app.js``` add following code to handle back button properly
```
application.android.on(application.AndroidApplication.activityBackPressedEvent, data => {
  router.back()
  data.cancel = true
})
```
