### ISSUE TITLE
ListView itemTap camelCase bug

### ISSUE THREAD

**Issue by GERJohnson** [rigor789/nativescript-vue#57]
If I use @itemTap attribute for the ListView I can call the tap event but get always a warning in the console:

Found camelCase attribute: @itemTap="onItemTap". HTML is case-insensitive. Use @item-tap="onItemTap" instead. Vue will automatically interpret it as camelCase in JavaScript. If this is an SVG camelCase attribute, use the .camel modifier.

If I change it to @item-tap="onItemTap" as suggested the tap event is no longer triggered.

**Comment by rigor789** [comment]
Hey @GERJohnson, i just got the chance to take a look at this, but I can't seem to get a warning, can you check if it is still an issue?

**Comment by GERJohnson** [comment]
yep still the case... used fresh installation to test it nativescript-vue@0.1.24 .. 


<img width="1671" alt="screen shot 2017-11-18 at 16 11 50" src="https://user-images.githubusercontent.com/21923568/32981896-422f29ca-cc7b-11e7-8c89-5ed8afa980be.png">

**Comment by rigor789** [comment]
Oh that is coming from the https://github.com/vuejs/vue-template-validator package, since you are using the rollup template. That is just a warning, feel free to ignore it, although it is a little annoying, it doesn't break the build. In the future we will focus on the webpack template, and if it has this issue we will figure a way to hide / ignore it.
