### ISSUE TITLE
tns run ios error(real device)

### ISSUE THREAD

**Issue by seohangyu** [rigor789/nativescript-vue#94]
There is no problem with the emulator. However, after connecting the actual device and typing 'tns run ios', the following problems will occur. How should we solve it?

![2017-11-30 7 33 15](https://user-images.githubusercontent.com/23069763/33426494-5c036ea4-d605-11e7-82c3-d74abd46bf23.png)

**Comment by rigor789** [comment]
Looks like an iOS provisioning issue, which I'm not really familiar with (I work on a linux machine), but I'm pretty sure you need to create a provisioning profile to deploy to a real device. I think that can be done in xcode.

**Comment by seohangyu** [comment]
What is Provisioning? There were many questions about this, but I did not see a solution. How do I create a provisioning file?

**Comment by rigor789** [comment]
This is what I found: https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppStoreDistributionTutorial/CreatingYourTeamProvisioningProfile/CreatingYourTeamProvisioningProfile.html 

Basically in order to run the app on a real device you need to sign the app with a key (or something along these lines), otherwise you can't run it on a device. This is over-complicated to be honest, but Apple is Apple ¯\_(ツ)_/¯

**Comment by seohangyu** [comment]
Wow .. It's complicated. Thanks ^^

**Comment by jlooper** [comment]
@seohangyu do you want to close this issue?
